# Generated by Django 4.0.6 on 2022-08-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_pub_date_blogpost_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
